# Generated by Django 5.1.1 on 2024-09-26 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('birt_date', models.DateField(null=True)),
                ('memorial_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AppoitmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('paided_customer', models.BooleanField(default=False)),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_level', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('S', 'Severe'), ('D', 'Deadly')], default='M', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.allergy')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pets.animaltype'),
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.animaltype')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pets.breed'),
        ),
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.customer'),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pets', models.ManyToManyField(to='pets.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.customer')),
            ],
        ),
        migrations.CreateModel(
            name='VeterinaryAppoitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('veterinarian', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('reason', models.CharField(choices=[('C', 'Checkup'), ('V', 'Vaccine'), ('I', 'Injury'), ('D', 'Digestive'), ('S', 'Skin'), ('E', 'Dental'), ('B', 'Behavior'), ('P', 'Parasite'), ('R', 'Reproduction'), ('O', 'Other')], default='C', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.animal')),
            ],
        ),
        migrations.CreateModel(
            name='AppoitmnetMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appoitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.veterinaryappoitment')),
            ],
        ),
    ]
