# Generated by Django 5.1.1 on 2024-09-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppoitmnetMedication',
            new_name='AppoitmentMedication',
        ),
    ]
