# Generated by Django 5.1.1 on 2024-09-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_appoitmnetmedication_appoitmentmedication'),
    ]

    operations = [
        # Add default values to the created_at and updated_at columns for pets_animal
        migrations.RunSQL(
            sql="""
                ALTER TABLE pets_animal
                MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
                ALTER TABLE pets_animal
                MODIFY COLUMN created_at TIMESTAMP;
            """
        ),
        
        migrations.RunSQL(
            sql="""
                ALTER TABLE pets_animal
                MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
                ALTER TABLE pets_animal
                MODIFY COLUMN updated_at TIMESTAMP;
            """
        ),
        
        # Add default values to the created_at and updated_at columns for pets_animalallergy
        migrations.RunSQL(
            sql="""
                ALTER TABLE pets_animalallergy
                MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
                ALTER TABLE pets_animalallergy
                MODIFY COLUMN created_at TIMESTAMP;
            """
        ),
        
        migrations.RunSQL(
            sql="""
                ALTER TABLE pets_animalallergy
                MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
                ALTER TABLE pets_animalallergy
                MODIFY COLUMN updated_at TIMESTAMP;
            """
        ),
        
        # Add default values to the created_at and updated_at columns for pets_appoitmentlog
        migrations.RunSQL(
            sql="""
                ALTER TABLE pets_appoitmentlog
                MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
                ALTER TABLE pets_appoitmentlog
                MODIFY COLUMN created_at TIMESTAMP;
            """
        ),
        
        migrations.RunSQL(
            sql="""
                ALTER TABLE pets_appoitmentlog
                MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
                ALTER TABLE pets_appoitmentlog
                MODIFY COLUMN updated_at TIMESTAMP;
            """
        ),
        
        # Add default values to the created_at and updated_at columns for pets_appoitmentmedication
        migrations.RunSQL(
            sql="""
                ALTER TABLE pets_appoitmentmedication
                MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
                ALTER TABLE pets_appoitmentmedication
                MODIFY COLUMN created_at TIMESTAMP;
            """
        ),
        
        # Add default values to the created_at and updated_at columns for pets_customer
        migrations.RunSQL(
            sql="""
                ALTER TABLE pets_customer
                MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
                ALTER TABLE pets_customer
                MODIFY COLUMN created_at TIMESTAMP;
            """
        ),
        
        migrations.RunSQL(
            sql="""
                ALTER TABLE pets_customer
                MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
                ALTER TABLE pets_customer
                MODIFY COLUMN updated_at TIMESTAMP;
            """
        ),
        
        # Add default values to the created_at and updated_at columns for pets_veterinaryappoitment
        migrations.RunSQL(
            sql="""
                ALTER TABLE pets_veterinaryappoitment
                MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
                ALTER TABLE pets_veterinaryappoitment
                MODIFY COLUMN created_at TIMESTAMP;
            """
        ),
         
        migrations.RunSQL(
            sql="""
                ALTER TABLE pets_veterinaryappoitment
                MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
                ALTER TABLE pets_veterinaryappoitment
                MODIFY COLUMN updated_at TIMESTAMP;
            """
        ),
            
    ]
